- name: Installing Apache and firewall port
  hosts: host2
  become: true
  
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Start Apache
    service:
      name: apache2
      state: started
      enabled: yes

  - name: apt update
    apt:
      update_cache: yes 

  - name: "install firewalld"
    apt:
      name: firewalld
      state: present

  - name: Open port 80 for apache2
    firewalld:
      service: http
      permanent: true
      state: enabled
  
  - name: Firewalld restart
    service:
      name: firewalld
      state: reloaded