- name: Copy Files To Clients
  hosts: all
  become: true

  tasks:
  - name: "Copy File"
    copy:
        src: /home/prabin/Downloads/script.rpm.sh
        dest: /tmp
        owner: ubuntu
        group: ubuntu
        mode: '0644'
